version: '3'

services:
  python_app:
   image: h3x89/python_app # my image on docker hub
  #  image: python_app # local built image
   ports:
     - 5000
   environment:
     - SERVICE_PORTS=5000
   deploy:
     replicas: 2
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - python_app
    environment:
      # - BALANCE=leastconn
      - BALANCE=roundrobin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
